[package]
name = "big_array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "*"
big_array_derive = { path = "big_array_derive" }